#!/bin/bash

# A shell script to submit farm jobs

# 1st version Ken Livingston, Nov 2007
# Modified from Jlab auger to pbs / torque - Ken Livingston Feb 2014

# function defs first,  main script below that.


exe=`basename $0`
print_usage()
{
    echo
    echo "Description: A shell script to submit jobs to a pbs / torque batch farm queue."
    echo
    echo "Usage: $exe [-r] [-s sleep] [-m <maxjobs>] <jobdir>|<jobfile>"
    echo
    echo "Options:"
    echo "  -m <maxjobs>   Set the maximum no of user owned jobs on the farm (default = 500)"
    echo "  -s <sleep>     Sleep time(s) between submitting jobs (default = 1s)"
    echo "  -r             Submit jobs in reverse order to their directory listing in <jobdir> "

    echo "Attempts to run qsub to submit <jobfile>, or all the *.sub files in <jobdir>"
    echo "For each jobfile, a test is made to see if jobfile.done exists. If so, the assumption is"
    echo "that the file has already been submitted. To allow resubmission, the .done file must be removed manually" 
    echo "The log of the each jsub command is put in <jobfile>.done"
    echo "Furthermore, no jsub commands will be executed until there are less than <maxjobs> jobs pending" 
    echo "or running on the farm (counted using the jobstat comand)"
    echo "The maximum no of jobs can be adjusted using the -m option. (default = 500)"
    echo "If there are more than <maxjobs>, the script will loop, testing every hour until it is able to"
    echo "submit another job."
    echo 
    echo "For each jobs to be submitted this script checks for the existence of the data files on the local farm RAID."
    echo 
    echo "Examples:"
    echo
    echo "$exe jobs/g13/pass0/v7/batch1/runs53764-53783.sub"
    echo "Submits  jobs/g13/pass0/v7/batch1/runs53764-53783.sub with result in jobs/g13/pass0/v7/batch1/runs53764-53783.sub.done"
    echo
    echo "$exe -m 1000 jobs/g13/pass0/v7/batch1"
    echo "Submits all .sub files in jobs/g13/pass0/v7/batch1, with logs in corresponding .done files,"
    echo "also increasing the maximum no of jobs to 1000." 
    echo 
    exit;
}

init_values()
{
#set the defaults
    sleeptime=0;
    default_maxq="3000";
    rev="";
    maxq="${default_maxq}";
    waittime="5m";
}

#  Function to set the command line options
function set_option {
 	case $1 in
        R)
            resubmit=1
            ;;
	    m)
	    maxq="${OPTARG}" ;;
	    s)
	    sleeptime="${OPTARG}" ;;
	    r)
	    rev="-r" ;;
            *)
	    print_usage ;;
	esac
    shift $[OPTIND-1]
} 

################################################################################################
#MAIN SCRIPT STARTS HERE

if [ $# -lt 1 ]; then
     print_usage;
fi

init_values;

#parse the command options and set variables accordingly
while getopts "m:s:r:R" opt ; do 
    set_option $opt  
done
shift $[$OPTIND-1]

#work out if we have a file or directory ( or neither)
if [ -f "$1" ]; then
    #make a filelist with a single file, for consistency
    dir=`dirname $1`
    rm -f ${dir}/allsubs.dat
    echo $1 > ${dir}/allsubs.dat
else
    dir=$1
    if [ -d "$dir" ]; then
	#make a filelist of all files
	rm -f ${dir}/allsubs.dat
	ls $rev $dir/*.sub > ${dir}/allsubs.dat
    else
	echo "Fatel Error: $1 doesn't seem to exist"
	print_usage
    fi
fi

#loop over all files in ${dir}/allsubs.dat

if [ "$resubmit" == "1" ]; then
    echo "Resubmitting"
    rm ${dir}/*.done
    rm ${dir}/Acqu_*
fi

while read subfile
do
    #if not already submitted (ie no .done file)
    if [ ! -f "${subfile}.done" ]; then

	#copy the files to the local raid if required by getting the info from the comments at top of the jobfile
	#get the stuff after the keyword in each requiredline
	LocalDir=`gawk -v f1="#InputDir: " '{if($0~f1){sub(f1,"");print $0}}' ${subfile}`
	InputFile=`gawk -v f1="#InputFile: " '{if($0~f1){sub(f1,"");print $0}}' ${subfile}`

	#if there are files to be copied (ie non zero list of files) 
	if [ ! -z $InputFile ]; then
	    echo "Checking for file on local RAID: $InputFile"

	    LocalFile=${LocalDir}"/"${InputFile}
	    
	    if [ ! -f $LocalFile ]; then
		echo "Not found as $LocalFile"
		exit 1
	    else
		echo "Found $LocalFile"
	    fi
	fi
	
	#OK to go
	qsub $subfile >& ${subfile}.done
	if [ $? -ne 0 ]; then
		echo "Error submitting job:"
		cat  ${subfile}.done
		echo "Aborting..."
		rm ${subfile}.done
		exit 1
	fi
	sleep $sleeptime
    else
	echo "$subfile was submitted previously."
    fi

done < ${dir}/allsubs.dat


exit;
