#!/bin/sh
# This is called from the when a farm job is submitted to a node.
# It cannot take arguments, rather it picks up environmental variables 
#
# Currently expecting the following to be set up in the submission script.
# ACQU_MAINDIR:       Location of the Acqu main directory
# ACQU_SETUPFILE:     Top level AcquRoot setup file
# ACQU_INPUTDIR:      Location of the Acqu data files on /local/raid
# ACQU_OUTPUTDIR:     Where to put the output on /local/raid
# ACQU_BASENAME:      Basename of this job
# ACQU_NODEDIR:       Where to store temporary files
# ACQU_INPUTFILE:     File to analyze
 
cd ${ACQU_MAINDIR}

# Make any required directories
mkdir -p ${ACQU_NODEDIR}

# Create log file for this process
LogFile="${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_AcquNode.log"

# Now run AcquRoot in batch mode
echo "AcquRoot --batch --batchdir ${ACQU_NODEDIR}/ --directory ${ACQU_NODEDIR}/ --datafile ${ACQU_INPUTDIR}/${ACQU_INPUTFILE} ${ACQU_SETUPFILE} &> $LogFile"
AcquRoot --batch --batchdir ${ACQU_NODEDIR}/ --directory ${ACQU_NODEDIR}/ --datafile ${ACQU_INPUTDIR}/${ACQU_INPUTFILE} ${ACQU_SETUPFILE} &> $LogFile

# List all the files in the output directory
echo 
echo "List all the files in the output directory:" 
echo "ls -lrt ${ACQU_NODEDIR}/" 
ls -lrt ${ACQU_NODEDIR}/
echo

# Copy output root files to raid array
echo "Copying all the files from temporary directory ${ACQU_NODEDIR} to ${ACQU_OUTPUTDIR}"
echo
echo "cp ${ACQU_NODEDIR}/*.root ${ACQU_OUTPUTDIR}/root/" 
cp ${ACQU_NODEDIR}/*.root ${ACQU_OUTPUTDIR}/root/

# Copy output log files to raid array
echo "cp ${ACQU_NODEDIR}/AcquRoot.log ${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_AcquRoot.log"
cp ${ACQU_NODEDIR}/AcquRoot.log ${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_AcquRoot.log

echo "cp ${ACQU_NODEDIR}/Analysis.log ${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_Analysis.log"
cp ${ACQU_NODEDIR}/Analysis.log ${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_Analysis.log

# DataServer.log does not exist for MC running, so check if it exists first
if [ -e ${ACQU_NODEDIR}/DataServer.log ]; then
    echo "cp ${ACQU_NODEDIR}/DataServer.log ${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_DataServer.log"
    cp ${ACQU_NODEDIR}/DataServer.log ${ACQU_OUTPUTDIR}/log/${ACQU_BASENAME}_DataServer.log
fi
echo

# Delete files and directory from local scratch
echo "deleting temporary directory ${ACQU_NODEDIR}" 
echo "/bin/rm -f  ${ACQU_NODEDIR}/*.*" 
/bin/rm -f ${ACQU_NODEDIR}/*.*
echo "rmdir ${ACQU_NODEDIR}"
rmdir ${ACQU_NODEDIR}

exit 0;
